// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBJ9LffwcCruPwWP-OV82fMF590hDAJDg',
    appId: '1:969445699566:web:bd2bc3d00a64e770c868ff',
    messagingSenderId: '969445699566',
    projectId: 'todoapp-1945f',
    authDomain: 'todoapp-1945f.firebaseapp.com',
    storageBucket: 'todoapp-1945f.firebasestorage.app',
    measurementId: 'G-201TYX1J9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_lDw-cheCR84IyTR4W9pNxLq96WkeEQ',
    appId: '1:969445699566:android:2d5ba7b0d4bf5783c868ff',
    messagingSenderId: '969445699566',
    projectId: 'todoapp-1945f',
    storageBucket: 'todoapp-1945f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbsnMTcgjeKeSbIYROEBXbxUGsyV_cRE',
    appId: '1:969445699566:ios:c8596716ec3c01edc868ff',
    messagingSenderId: '969445699566',
    projectId: 'todoapp-1945f',
    storageBucket: 'todoapp-1945f.firebasestorage.app',
    iosClientId: '969445699566-vcuua6nsj8st9shtm3dt4hqlevcsm9du.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkbsnMTcgjeKeSbIYROEBXbxUGsyV_cRE',
    appId: '1:969445699566:ios:c8596716ec3c01edc868ff',
    messagingSenderId: '969445699566',
    projectId: 'todoapp-1945f',
    storageBucket: 'todoapp-1945f.firebasestorage.app',
    iosClientId: '969445699566-vcuua6nsj8st9shtm3dt4hqlevcsm9du.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBJ9LffwcCruPwWP-OV82fMF590hDAJDg',
    appId: '1:969445699566:web:03e7d423fb2373a8c868ff',
    messagingSenderId: '969445699566',
    projectId: 'todoapp-1945f',
    authDomain: 'todoapp-1945f.firebaseapp.com',
    storageBucket: 'todoapp-1945f.firebasestorage.app',
    measurementId: 'G-PV2NLYPDLR',
  );
}
